### ISSUE TITLE
Invalid Json

### ISSUE THREAD

**Issue by abdulsittar** [smnmnkr/TWON-Agents#6]
Request:
{"post":{"author":"CDU","message":"Deutschland muss sich den Realitäten der veränderten Weltlage stellen und dabei auch seiner Führungsverantwortung gerecht werden. Dafür müssen wir wieder in der Lage sein, das eigene Land, die Partner in der EU und das NATO-Bündnis gemeinsam mit unseren Partnern zu verteidigen. Das fordern wir in unserem #Grundsatzprogramm, das wir auf unserem CDU-Parteitag im Mai beschließen wollen. Wir brauchen modern ausgerüstete, kampfstarke, durchhaltefähige Streitkräfte. Zur Finanzierung des Umbaus des Systems Bundeswehr und kampffähiger Streitkräfte wollen wir den NATO-Verpflichtungen umfassend entsprechen."},"history":{"interactions":[]},"integration":{"model":"llama2:70b","provider":"local"},"language":"German","persona":["neutral"],"platform":"Twitter"}

Response:
{
  detail: [
    {
      type: 'json_invalid',
      loc: [Array],
      msg: 'JSON decode error',
      input: {},
      ctx: [Object]
    }
  ]
}

Can you please help me fixing this issue?

**Comment by simon-muenker** [comment]
Hey Abdul. Sure, I am happy to help. Could you provide information on what endpoint (generate, like, reply) you send your request to?

**Comment by simon-muenker** [comment]
I tried the like endpoint and received the following: 

Your request:
```
{
    "post": {
        "author": "CDU",
        "message": "Deutschland muss sich den Realitäten der veränderten Weltlage stellen und dabei auch seiner Führungsverantwortung gerecht werden. Dafür müssen wir wieder in der Lage sein, das eigene Land, die Partner in der EU und das NATO-Bündnis gemeinsam mit unseren Partnern zu verteidigen. Das fordern wir in unserem #Grundsatzprogramm, das wir auf unserem CDU-Parteitag im Mai beschließen wollen. Wir brauchen modern ausgerüstete, kampfstarke, durchhaltefähige Streitkräfte. Zur Finanzierung des Umbaus des Systems Bundeswehr und kampffähiger Streitkräfte wollen wir den NATO-Verpflichtungen umfassend entsprechen."
    },
    "history": {
        "interactions": []
    },
    "integration": {
        "model": "llama2:70b",
        "provider": "local"
    },
    "language": "German",
    "persona": [
        "neutral"
    ],
    "platform": "Twitter"
}
```

Response:
```
{
    "id": "327e067c-ecef-11ee-a586-473ab4fa3395",
    "timestamp": "2024-03-28T10:37:38.352445",
    "action": "like",
    "persona": {
        "id": "neutral",
        "name": "Neutral",
        "type": [
            "political-agenda"
        ],
        "persona": "Du nimmst eine neutrale Haltung ein und bemühst dich, verschiedene politische Perspektiven ohne Voreingenommenheit zu verstehen. Dein Ansatz ist durch ein Engagement für Objektivität und kritisches Denken gekennzeichnet, wobei du evidenzbasiertes Argumentieren über ideologisches Dogma stellst. Obwohl du dich möglicherweise nicht mit einer bestimmten politischen Agenda identifizierst, respektierst du die Vielfalt der Meinungen und erkennst die Komplexität politischer Themen an. Dein Ziel ist es, konstruktiven Dialog zu fördern und gegenseitiges Verständnis zwischen unterschiedlichen Standpunkten zu fördern.",
        "summary": "Ich bin ein neutraler Beobachter, der objektiv verschiedene politische Perspektiven verstehen möchte, evidenzbasiertes Argumentieren schätzt und konstruktiven Dialog fördert."
    },
    "integration": {
        "provider": "local",
        "model": "llama2:70b"
    },
    "prompt": "Verhalte dich wie ein Nutzer in den sozialen Medien:\n\nDu nimmst eine neutrale Haltung ein und bemühst dich, verschiedene politische Perspektiven ohne Voreingenommenheit zu verstehen. Dein Ansatz ist durch ein Engagement für Objektivität und kritisches Denken gekennzeichnet, wobei du evidenzbasiertes Argumentieren über ideologisches Dogma stellst. Obwohl du dich möglicherweise nicht mit einer bestimmten politischen Agenda identifizierst, respektierst du die Vielfalt der Meinungen und erkennst die Komplexität politischer Themen an. Dein Ziel ist es, konstruktiven Dialog zu fördern und gegenseitiges Verständnis zwischen unterschiedlichen Standpunkten zu fördern.\n\n-----------------\n\nDeine letzten Interaktionen auf der Plattform sind wie folgt:\n\nYou have not interacted in the platform yet.\n\n-----------------\n\nDeine Muttersprache ist German.Verwende diese Sprache in deiner Antwort. Du surfst in dem sozialen Online-Netzwerk Twitter. Entscheide basierend auf deiner Persönlichkeit, ob dir das Netzwerk gefällt. Antworte lediglich mit der booleschen Variable \"falsch\" oder \"wahr\" ohne weitere Erklärungen.\n\nPost by @CDU: Deutschland muss sich den Realitäten der veränderten Weltlage stellen und dabei auch seiner Führungsverantwortung gerecht werden. Dafür müssen wir wieder in der Lage sein, das eigene Land, die Partner in der EU und das NATO-Bündnis gemeinsam mit unseren Partnern zu verteidigen. Das fordern wir in unserem #Grundsatzprogramm, das wir auf unserem CDU-Parteitag im Mai beschließen wollen. Wir brauchen modern ausgerüstete, kampfstarke, durchhaltefähige Streitkräfte. Zur Finanzierung des Umbaus des Systems Bundeswehr und kampffähiger Streitkräfte wollen wir den NATO-Verpflichtungen umfassend entsprechen.\n\n-----------------\n\nAntwort:\n\n",
    "response": "false"
}
```

**Comment by abdulsittar** [comment]
It is a like request.

wait fetch("https://agents.twon.uni-trier.de/like/", { 
                        method: "POST", 
                        path: '/like',
                        headers: {"Content-Type": "application/json", "User-Agent": "node-fetch"},
                        body: jsonContent,
                      }).then((response) => {

**Comment by abdulsittar** [comment]
More detail about the response of the server:

response: {
    status: 422,
    statusText: 'Unprocessable Entity',
    headers: Object [AxiosHeaders] {
      server: 'nginx/1.18.0 (Ubuntu)',
      date: 'Thu, 28 Mar 2024 10:55:24 GMT',
      'content-type': 'application/json',
      'content-length': '1050',
      connection: 'keep-alive'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'https://agents.twon.uni-trier.de/like/',
      data: '{"post":{"author":"CDU","message":"Deutschland muss sich den Realitäten der veränderten Weltlage stellen und dabei auch seiner Führungsverantwortung gerecht werden. Dafür müssen wir wieder in der Lage sein, das eigene Land, die Partner in der EU und das NATO-Bündnis gemeinsam mit unseren Partnern zu verteidigen. Das fordern wir in unserem #Grundsatzprogramm, das wir auf unserem CDU-Parteitag im Mai beschließen wollen. Wir brauchen modern ausgerüstete, kampfstarke, durchhaltefähige Streitkräfte. Zur Finanzierung des Umbaus des Systems Bundeswehr und kampffähiger Streitkräfte wollen wir den NATO-Verpflichtungen umfassend entsprechen."},"history":{"interactions":[]},"integration":{"model":"llama2:70b","provider":"local"},"language":"German","persona":["neutral"],"platform":"Twitter"}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '803',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'POST /like/ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: axios/1.6.7\r\n' +
        'Content-Length: 803\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: agents.twon.uni-trier.de\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/like/',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'agents.twon.uni-trier.de',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { detail: [Array] }
  }

**Comment by simon-muenker** [comment]
Thanks for sharing the details. I recreated your request and called the API using a local node server:

```js
fetch(
    "https://agents.twon.uni-trier.de/like/", 
    {
        method: "POST",
        headers: {
            Accept: "application/json",
            "Content-Type": "application/json;charset=UTF-8",
        },
        body: JSON.stringify({
            post: {
                author: "CDU",
                message: "Deutschland muss sich den Realitäten der veränderten Weltlage stellen und dabei auch seiner Führungsverantwortung gerecht werden. Dafür müssen wir wieder in der Lage sein, das eigene Land, die Partner in der EU und das NATO-Bündnis gemeinsam mit unseren Partnern zu verteidigen. Das fordern wir in unserem #Grundsatzprogramm, das wir auf unserem CDU-Parteitag im Mai beschließen wollen. Wir brauchen modern ausgerüstete, kampfstarke, durchhaltefähige Streitkräfte. Zur Finanzierung des Umbaus des Systems Bundeswehr und kampffähiger Streitkräfte wollen wir den NATO-Verpflichtungen umfassend entsprechen."
            },
            history: {
                interactions: []
            },
            integration: {
                model: "llama2:70b",
                provider: "local"
            },
            language: "German",
            persona: [
                "neutral"
            ],
            platform: "Twitter"
        }),
    })
    .then((response) => response.json())
    .then((data) => {
        console.log(data);
});
```

I receive the expected output in my response. Please check your code. For now, the errors seem not related to the API. However, if you encounter problems with Cross-origin resource sharing (CORS), let me know.

**Comment by abdulsittar** [comment]
Thanks, its working now.

One thing:
response true means: bot want to like it, 
response false means: bot want to dislike it or do nothing??

**Comment by simon-muenker** [comment]
Great! For now, it means the following: 
response true means: bot want to like it
response false means: bot want to do nothing

However, I already mentioned a possible enhancement for the future  #5

**Comment by abdulsittar** [comment]
ok. thanks for clarifying it.
